### PR TITLE
Libresprite

### PR DESCRIPTION
**Pull request by Muvkina**
Not sure what happened to my other pull request. Not very good with git yet. But here. I believe I fixed everything.

### CODE REVIEW

**Comment by eudaldgr** [comment]
Checksums are missing, dependencies must be in alphabetical order, last flag of build script without `\` and some identation faults.

**Comment by Muvkina** [comment]
Fixed

**Comment by eudaldgr** [comment]
Checksums are missing.

**Comment by Muvkina** [comment]
I reran kiss c and added the changes to the commit...

**Comment by Muvkina** [comment]
Only packages that have locally stored files create checksums I just remembered. Since this is git and there are no local files checksums aren't generated by kiss.

**Comment by Muvkina** [comment]
You can see this on any other git package as well such as tinyramfs.

**Comment by eudaldgr** [comment]
That’s wrong, [this](https://github.com/eudaldgr/kiss-repo/blob/7c768edf7b9c46ec9a294ce51f18df0e38fc3ce3/kernel/tinyramfs/checksums) is created with `kiss c`

**Comment by eudaldgr** [comment]
And if this was true why add a empty file? In the two cases something will be fixed.

**Comment by Muvkina** [comment]
The file was created from kiss-new. I have run kiss c multiple times and there is no contents put in the checksums file. Also even though I believe even if there isnt anything in the checksums the package manager needs that file. However that last bit may be incorrect. I can confirm this package works though I have built it many times same with my tinyramfs in my repo which also has nothing in the checksums.

**Comment by Muvkina** [comment]
Yes I can confirm what I wrote deleting the checksums file causes the package to fail with checksums missing. Re running kiss c creates and empty checksums file and then building works. You can test this yourself.

**Comment by eudaldgr** [comment]
That's my fault, this is something [new](https://github.com/kisslinux/kiss/releases/tag/5.0.0) under the lasts 3 days for the package manager.

**Comment by Muvkina** [comment]
No worries

**Pull request merged**
